services:
  - type: web
    name: news-classifier
    env: python
    runtime: python-3.11.9  # Matches your runtime.txt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
